# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed61d8c98d9d2691712c7f462bdc5378b1927bba18113178f94df87bc76e79a192f1c0030fdc50ce075b46f85d7263a9136d042c48b6a5a374cce6f178d6b35

test:
  secret_key_base: e538dacd8dba59e96b02616af6918ef4fe9dbd723f09ba7b3603d2f80d43530686b0f7cf743ffa1fd6a5653c850347d9741a20bbf8eed599bc1650c4e813363e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
